### PR TITLE
Remove typo words

### PR DESCRIPTION
**Pull request by Shrenne**

### CODE REVIEW

**Review by iminlikewithyou — APPROVED** [review]
WONDERFUL

**Review by tollt — DISMISSED** [review]
These words are mistakes, so should be removed. Approved.

**Review by iminlikewithyou — APPROVED** [review]
nice fix

**Review by tollt — APPROVED** [review]
Yeah Looks Good

**Review by RegularCookiez — APPROVED** [review]
you have included invalid typos which should definitely be removed from the game, approved

**Pull request merged**
